# Generated by Django 5.2.6 on 2025-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_credits_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
