# Generated by Django 5.2.6 on 2025-10-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
