# Generated by Django 5.2.6 on 2025-10-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='file_extension',
            field=models.CharField(default='c', max_length=10),
        ),
    ]
