# Generated by Django 5.2.6 on 2025-10-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exercise_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='extra_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
