# Generated by Django 5.2.6 on 2025-10-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_exercise_extra_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='file_extension',
            field=models.CharField(default='.c', max_length=10),
        ),
    ]
