# Generated by Django 5.2.6 on 2025-10-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_exercise_file_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='file_extension',
            field=models.CharField(default='.cu', max_length=10),
        ),
    ]
