# Generated by Django 5.2.6 on 2025-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_exercise_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='include_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
