# Generated by Django 5.2.6 on 2025-10-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_exercise_include_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='extra_files',
        ),
    ]
